# **What is NumPy?**
- is a Python library.

- NumPy is used for working with arrays.

- NumPy is short for "Numerical Python"

- A python package for Scientific computin.
  - discrete fourier transforms.
  - basic liner algebra.
  - basic statistical operation.

- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

# **Why Use NumPy?**
- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
- its needs less memory.
- Arrays are very frequently used in data science, where speed and resources are very important.

#**Why is NumPy Faster Than Lists?**

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.This behavior is called locality of reference in computer science.This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

# **Which Language is NumPy written in?**

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.



# **Importing library/ Array Atrributes**

In [5]:
# np.array
import numpy as np

a = np.array([1,2,3]) # 1-D / vector
print(a)

[1 2 3]


In [6]:
a


array([1, 2, 3])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.shape

(3,)

In [10]:
a.ndim

1

In [15]:
b = np.array([[1, 2, 3],
             [4, 5, 6]])  # 2-D / matrix

In [16]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
type(b)

numpy.ndarray

In [18]:
b.shape

(2, 3)

In [20]:
b.ndim

2

In [21]:
# 3-D arrays

c = np.array([[[1.0, 2, 3],
               [4, 5, 6],
               [7, 8, 9]]])

d = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],

             [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

In [22]:
c , d

(array([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [23]:
c.shape, d.shape

((1, 3, 3), (2, 3, 3))

In [24]:
a.dtype, b.dtype, c.dtype, d.dtype

(dtype('int64'), dtype('int64'), dtype('float64'), dtype('int64'))

In [25]:
a.size, b.size, c.size, d.size # determine how many elements are there in an array

(3, 6, 9, 18)

In [26]:
a.nbytes, b.nbytes, c.nbytes, d.nbytes # determine how many bytes consumed by an array

(24, 48, 72, 144)

# Array Creation

In [27]:
array1 = np.array([1, 2, 3], dtype = 'int')

In [28]:
array1

array([1, 2, 3])

In [30]:
zeros = np.zeros((3, 3), dtype = 'int')  # Return a new array of given shape and type, filled with zeros
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
ones = np.ones((3, 3), dtype = 'int') # Return a new array of given shape and type, filled with ones
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [34]:
full = np.full((2,3), 5) # Return a new array of given shape and type, filled with given value
full

array([[5, 5, 5],
       [5, 5, 5]])

In [35]:
identity = np.identity(3, dtype = 'int') # Return the identity array.
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [36]:
eye = np.eye(3,3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
arange = np.arange(1, 10, 2) # Return evenly spaced values within a given interval.
arange

array([1, 3, 5, 7, 9])

In [38]:
linspace = np.linspace(1, 100, 50, dtype = 'int') # Return evenly spaced numbers over a specified interval.
linspace

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [39]:
linspace.size

50

In [42]:
empty = np.empty((1,5)) # Return a new array of given shape and type, without initializing entries
empty

array([[1., 1., 1., 1., 1.]])

In [43]:
for i in range(5):
    empty[:,i] = i
empty

array([[0., 1., 2., 3., 4.]])

# Array indexing and Slicing

**indexing**

In [47]:
arr1 = np.array([1, 2, 3, 4, 5])

In [48]:
print( arr1 )

[1 2 3 4 5]


In [49]:
arr1[0]

1

In [50]:
arr1[3]

4

In [51]:
arr1[-1]

5

In [52]:

arr2 = np.random.randint(1, 10, size = (3,3))

In [53]:
print(arr2)

[[5 6 1]
 [9 4 2]
 [8 1 5]]


In [54]:
arr2[0][0]

5

In [55]:
arr2[1][1]

4

In [56]:
arr2[1, 1]

4

In [57]:
arr3 = np.random.randint(1, 10, size = (2, 3, 3))

In [58]:
print(arr3)

[[[7 7 2]
  [3 9 4]
  [3 2 3]]

 [[5 2 5]
  [2 8 3]
  [8 2 9]]]


In [59]:
arr3[0][1][1]

9

In [60]:
arr3[0, 1, 1]

9

In [61]:
arr3[1, 2, 1]

2

**Slicing**

In [62]:
print(arr1)

[1 2 3 4 5]


In [63]:
print(arr1[: 3])

[1 2 3]


In [64]:
print(arr1[2:])

[3 4 5]


In [65]:
arr2

array([[5, 6, 1],
       [9, 4, 2],
       [8, 1, 5]])

In [66]:
arr2[0: 2, 0:2]

array([[5, 6],
       [9, 4]])

In [67]:
arr2[1:, 1:]

array([[4, 2],
       [1, 5]])

# **Manipulating array shapes**

1. reshape
2. resize
3. flatten
4. revel
5. defining array shape

**reshape()**

In [68]:
a = np.array([[1, 2, 3],
            [4, 5, 6]])

In [69]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
a.shape

(2, 3)

In [71]:
a_reshaped = np.reshape(a, (3, 2)) # Gives a new shape to an array without changing its data.

In [72]:
a_reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
a_reshaped2 = np.reshape(a, (3, 3))

ValueError: cannot reshape array of size 6 into shape (3,3)

**resize()**

In [76]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
a_resized = np.resize(a, (4, 3)) # Return a new array with the specified shape.

In [78]:
a_resized

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [79]:
a_resized2 = np.resize(a, (3, 2))

In [80]:
a_resized2

array([[1, 2],
       [3, 4],
       [5, 6]])

**ravel()**

In [81]:
a = np.random.randint(1, 10, (2, 3)) # Return a view of the array

In [82]:
a

array([[3, 4, 8],
       [9, 3, 3]])

In [84]:
a_raveled = np.ravel(a)

In [85]:
a_raveled

array([3, 4, 8, 9, 3, 3])

In [86]:
a_raveled.shape

(6,)

In [87]:
a_raveled[0] = 0

In [88]:
a_raveled

array([0, 4, 8, 9, 3, 3])

In [89]:
a

array([[0, 4, 8],
       [9, 3, 3]])

**flatten()**

In [90]:
a

array([[0, 4, 8],
       [9, 3, 3]])

In [91]:
a_flattened = a.flatten() # Return a copy of the array, always allocates a new memory.

In [92]:
a_flattened

array([0, 4, 8, 9, 3, 3])

In [93]:
a_flattened[0] = 100

In [94]:
a_flattened

array([100,   4,   8,   9,   3,   3])

In [95]:
a

array([[0, 4, 8],
       [9, 3, 3]])

**defining an array shape**

In [96]:
a

array([[0, 4, 8],
       [9, 3, 3]])

In [97]:
a.shape = (3, 2)

In [98]:
a

array([[0, 4],
       [8, 9],
       [3, 3]])

In [100]:
a.shape = (5, 2)

ValueError: cannot reshape array of size 6 into shape (5,2)

#**Stacking**

**Horizontal Stacking**

In [101]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
b = 2*a

In [103]:
b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [104]:
np.hstack((a, b))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [105]:
np.column_stack((a, b))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [106]:
np.concatenate((a, b), axis = 1)

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

**Vertical Stacking**

In [107]:
np.vstack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [108]:
np.row_stack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [109]:
np.concatenate((a, b), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

**Depth Stack**

In [110]:
np.dstack((a, b))

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])